server:
  port: 8082 
spring: 
  datasource:
    url: jdbc:mysql://localhost:3306/doccure_uaa
    username: root
    password: 
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    
    hikari:
      poolName: Hikari
      maximum-pool-size: 10
      minimum-idle: 10
      idle-timeout: 10000
      max-lifetime: 10000
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true 
  mail:
    host: smtp.gmail.com
    username: developer.binesh@gmail.com   
    password: developerbinesh
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            
  jpa: 
    show-sql: true
    
auth:    
  token:
    base64-secret: ODMwNTNiY2JhNDA4ODI5ZDljNDJkMThlZTE2ZDVjMDljNTAzZTBmN2U1MTk0ZDFjYzg5NWZkZjFjNzhhM2FkZGM4YzcxZDg1OGI1MDQyNjdkYjFiN2FhZDViNGY2M2ViMmUzM2YxYzI5MmIyZGNkY2Q5NDAwZTQ5NGQ2OTNiYjM=
        # Token is valid 24 hours
    token-validity-in-seconds: 86400
    token-validity-in-seconds-for-remember-me: 2592000


auth:    
  token:
    base64-secret: ODMwNTNiY2JhNDA4ODI5ZDljNDJkMThlZTE2ZDVjMDljNTAzZTBmN2U1MTk0ZDFjYzg5NWZkZjFjNzhhM2FkZGM4YzcxZDg1OGI1MDQyNjdkYjFiN2FhZDViNGY2M2ViMmUzM2YxYzI5MmIyZGNkY2Q5NDAwZTQ5NGQ2OTNiYjM=
        # Token is valid 24 hours
    token-validity-in-seconds: 86400
    token-validity-in-seconds-for-remember-me: 2592000