server:
  port: 8083
spring:
  kafka:
    consumer:
      auto-offset-reset: earliest  
  datasource:
    url: jdbc:mysql://localhost:3306/doccure_practices
    username: root
    password: 
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: DOCCURE_PAT_POOL
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
         
     
eureka:
  client:
    enabled: false
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
     hostname: localhost           

auth:    
  token:
    base64-secret: ODMwNTNiY2JhNDA4ODI5ZDljNDJkMThlZTE2ZDVjMDljNTAzZTBmN2U1MTk0ZDFjYzg5NWZkZjFjNzhhM2FkZGM4YzcxZDg1OGI1MDQyNjdkYjFiN2FhZDViNGY2M2ViMmUzM2YxYzI5MmIyZGNkY2Q5NDAwZTQ5NGQ2OTNiYjM=
        # Token is valid 24 hours
    token-validity-in-seconds: 86400
    token-validity-in-seconds-for-remember-me: 2592000